version: 0.0
os: linux
files:
    - source: /
      destination: /home/ubuntu/node
permissions:
    - object: /
      pattern: "**"
      owner: ubuntu
      group: ubuntu
hooks:
  AfterInstall:
    - location: scripts/install.sh
      timeout: 600
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 120
      runas: ubuntu
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 120
      runas: ubuntu